-- Create the database for the global Banking System to store User Details.
CREATE DATABASE GBSUSERSDB;
-- Switch to the GBSUSERSDB
USE GBSUSERSDB;
-- Create the USERS table to store the details of the bank customers
CREATE TABLE USERS(USER_NAME CHAR(50) PRIMARY KEY, USER_PASSWORD CHAR(50),
 CREATION_DATE CHAR(50), NUMBER_OF_ACCOUNTS CHAR(50), 
 TOTAL_BALANCE FLOAT, CONTACT_NUMBER CHAR(50));
 UPDATE USERS SET NUMBER_OF_ACCOUNTS = '2' WHERE USER_NAME = 'hansneilb';
 UPDATE USERS SET NUMBER_OF_ACCOUNTS = '2' WHERE USER_NAME = 'cristoph';
 UPDATE USERS SET TOTAL_BALANCE = '50000' WHERE USER_NAME = 'hansneilb';
 DELETE FROM USERS WHERE USER_NAME = 'John';
 SELECT * FROM USERS;
 DROP TABLE USERS;

 
 
 -- The database for the GBS to store Accounts and Transactions Details
 CREATE DATABASE GBSACCOUNTSDB;
 USE GBSACCOUNTSDB;
 DROP DATABASE GBSACCOUNTSDB;
 -- Table for Accounts
 CREATE TABLE ACCOUNTS (ACCOUNT_NUMBER INT PRIMARY KEY, USER_NAME CHAR(50),
 ACCOUNT_BALANCE double);
 INSERT INTO ACCOUNTS VALUES ('1',"hansneilb",'20000');
 INSERT INTO ACCOUNTS VALUES ('2',"hansneilb",'30000');
 INSERT INTO ACCOUNTS VALUES ('3',"cristoph",'50000');
 INSERT INTO ACCOUNTS VALUES ('4',"cristoph",'20000');
 SELECT *FROM ACCOUNTS;
 DROP TABLE ACCOUNTS;
 
 
 -- Table for Transactions
 CREATE TABLE TRANSACTIONS (TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
 FROM_ACCOUNT INT, TO_ACCOUNT INT, AMOUNT double);
 INSERT INTO TRANSACTIONS VALUES ('10','1','3','2000');
 SELECT * FROM TRANSACTIONS;
 DROP TABLE TRANSACTIONS;